### ISSUE TITLE
ViewModelEndpoint delete

### ISSUE THREAD

**Issue by davecoates** [prestojs/prestojs#84]
Currently no way to handle a delete in a ViewModelEndpoint

Don't see an easy way to achieve this with current hooks - response not available in transformResponseBody. May need something else?

**Comment by levic** [comment]
If you do a delete on a record, it can't remove that record from the cache automatically since the endpoint doesn't have a copy of the original record that was used to create the delete request

(ViewModel endpoint hooks into the transformresponsebody for update/create but for delete the server doesn't return the record, and you only have access to the body).

Probably transformresponsebody shouldn't have caching side effects, these should be done through a separate mechanism that is common for create/update/delete

**Comment by davecoates** [comment]
Another example of shortcoming. Say you have an endpoint that returns some extra data you want but you want the endpoint on the frontend to return the main record. eg.

Client list endpoint returns

```
{
   "Project": .... list of projects related to client ...,
   "Client": ... list of clients ...,
}
```

On frontend endpoint defined as

```
new ViewModelEndpoint(apiUrls.get('clientList'), {
    Client,
    Project,
});
```

so it correctly caches Client and Project

But when you call it you get back an object like `{ Client: ..., Project: ... }` when really you want just an array of `Client` records.

With current pipeline there's no way to transform it. You can add your own `transformResponseBody` but it's called _before_ the `ViewModelEndpoint` one which does the caching.
